### ISSUE TITLE
Errors while adding the Calendar component

### ISSUE THREAD

**Issue by multiwebinc** [shadcn/ui#201]
I have a new install using Next13 with `create-next-app` enabling the experimental app directory and  and then `npx shadcn-ui init`. When I try to install the calendar component, I get errors:

```
❯ npx shadcn-ui add calendar
Running the following command will overwrite existing files.
Make sure you have committed your changes before proceeding.

✔ Where would you like to install the component(s)? … ./components/ui
Installing 1 component(s) and dependencies...
⠦ Calendar...file:///home/mike/.npm/_npx/74755fd285ad77f7/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: npm install react-day-picker date-fns
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "react-day-picker date-fns" of package "react-day-picker date-fns": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in: /home/mike/.npm/_logs/2023-04-19T01_54_22_545Z-debug-0.log
    at makeError (file:///home/mike/.npm/_npx/74755fd285ad77f7/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/mike/.npm/_npx/74755fd285ad77f7/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///home/mike/.npm/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:406:9) {
  shortMessage: 'Command failed with exit code 1: npm install react-day-picker date-fns',
  command: 'npm install react-day-picker date-fns',
  escapedCommand: 'npm install "react-day-picker date-fns"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code EINVALIDTAGNAME\n' +
    'npm ERR! Invalid tag name "react-day-picker date-fns" of package "react-day-picker date-fns": Tags may not have any characters that encodeURIComponent encodes.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: /home/mike/.npm/_logs/2023-04-19T01_54_22_545Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v19.9.0
```

Executing `npm install react-day-picker date-fns` manually does not produce any errors:

```
❯ npm install react-day-picker date-fns

added 2 packages, and audited 370 packages in 4s

120 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**I'm using:** 
Node.js v19.9.0
NPM 9.6.4

**Comment by shadcn** [comment]
This is fixed. The date-fns dependency was missing.

**Comment by multiwebinc** [comment]
Yes, it is working for me now. Thanks.

**Comment by Blinks44** [comment]
Hm, today i've tried install calendar via ```npx shadcn-ui add calendar``` and get the same error

![2023-04-26_09-32-51](https://user-images.githubusercontent.com/8570193/234489756-c2f7feae-1f04-436f-986b-7884968c1e33.png)

**Comment by shadcn** [comment]
@Blinks44 Which version of `shadcn-ui` are you using and which package manager?

**Comment by Blinks44** [comment]
@shadcn package manager - npm, but i don't understand about version of shadcn-ui, i've just created fresh project -> npx shadcn-ui init -> npx shadcn-ui add calendar -> and booom, error.

Oh, and i don't use Next.js 13, just wanted to play around in Vite, all components work fine except the calendar.

**Comment by Blinks44** [comment]
Okey, now i know, that this is how npx is designed. To always use latest version of package preferable way is ```npx shadcn-ui@latest add calendar``` and problem is fixed

**Comment by mhaidarhanif** [comment]
@Blinks44 @shadcn Yea I think the docs would be better to tell the reader to always use `npx shadcn-ui@latest` then to prevent this problem.
