### ISSUE TITLE
Failed to fetch components from https://ui.shadcn.com/api/components

### ISSUE THREAD

**Issue by FilipeAPV** [shadcn/ui#646]
Error happens when I try to install a component. Ex: npx shadcn-ui add dropdown-menu

Have tried with different components, but got same result.

`
file:///C:/Users/username/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:34
    throw new Error(
          ^

Error: Failed to fetch components from https://ui.shadcn.com/api/components.
    at getAvailableComponents (file:///C:/Users/username/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:34:11)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (file:///C:/Users/username/AppData/Local/npm-cache/_npx/74755fd285ad77f7/node_modules/shadcn-ui/dist/index.js:361:33)
`
![Code_MatouNHaDA](https://github.com/shadcn/ui/assets/102620940/8af7c8b9-a166-449a-9c23-e9138476ea4a)

Do you have the same result from your side ?

Thank you

**Comment by cjfswd** [comment]
Same here, I suppose this might be happening because they just launched a new release a few minutes ago.

**Comment by shadcn** [comment]
Yes. Please use `npx shadcn-ui@latest add`. Notice the `@latest`.

**Comment by FilipeAPV** [comment]
Thank you very much @shadcn.

I needed to run `npx shadcn-ui@latest init` first, but after that, all worked fine.
